version: '3'

services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode=""
