version: '3'

services:

  api:
    image: golang:1.13.11-alpine3.11

    ports:
      - 8889:8889/tcp # gRPC
      - 8890:8890/tcp # HTTP (HC)
    environment:
      - DATABASE_ADDRESS=root:MYSQL_ROOT_PASSWORD@tcp(mysql:3306)/MYSQL_DATABASE
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ~/fullstack-code-challenge/api:/fullstack-code-challenge/api:consistent
    working_dir: /fullstack-code-challenge/api
    command: go run main.go

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=MYSQL_ROOT_PASSWORD
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode=""
